### PR TITLE
#259 Enhancement of text

### LINKED ISSUE #259: [DOCS] Enhancement of text.
**Describe the documentation update**
The text documentation is not properly visible causing problem for the mobile user to read it.

**Why is this needed?**
The font style  , size etc. can be changed to make it look elegant. 
It will also increase the intereactiveness of the page.

**Additional context**
Screenshot 2024-10-06 233951
Screenshot 2024-10-06 234004
Kindly refer to the above images for the issues I have mentioned.

Please assign me this issue under Hacktoberfest and gssoc '24 extended.

### PR DESCRIPTION
**Pull request by akansha-02**
# 🚀 Pull Request

## Description

Please include a summary of the changes and the related issue. Provide relevant motivation and context. List any dependencies that are required for this change.

Fixes #259 

before
Screenshot 2024-10-18 143823

after
Screenshot 2024-10-18 143831
Screenshot 2024-10-18 143844

please check PR i have made changes and now website is good to go in mobile view please assing this PR to me with level 2 badge

## Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by akbatra567** [comment]
@akansha-02, 
Could you have a look at the review slider as well ? 

Screenshot 2024-10-19 at 11 47 15 PM

**Comment by akansha-02** [comment]
Yes I will do it...also if you could then change the level to level 3.

**Comment by akansha-02** [comment]
Done with changes.
Please merge the PR.

**Comment by akbatra567** [comment]
Still can see the issue, merging for now, will fix this in another issue.
Screenshot 2024-10-22 at 10 21 24

**Pull request merged**
