### PR TITLE
Added navigation buttons in "Customer Review" section

### PR DESCRIPTION
**Pull request by swathivemula7**
# 🚀 Pull Request

Fixes issue no. #200

I have added the previous and next buttons to navigate between the customer reviews.
Capturendjfnd

Kindly review at the earliest...

### CODE REVIEW

**Comment by swathivemula7** [comment]
@07sumit1002 Kindly review the PR at the earliest

**Comment by Khushalsarode** [comment]
@07sumit1002 is the maintainer/owner tag and explain

**Comment by swathivemula7** [comment]
@akbatra567 Kindly review this PR

**Comment by swathivemula7** [comment]
@akbatra567 Kindly add labels of gssoc , hacktoberfest and a deserving level label...

**Pull request merged**
