### PR TITLE
#Add Create greetings.yml

### LINKED ISSUE #108: Add Github Greetings Bot
Hello! The project is missing a simple and customizable Greetings bot when someone new visits CabRental project and raises a new issue or a PR. This is a level1 enhancement. Please let me know if it is okay to set this one up! 💫

### PR DESCRIPTION
**Pull request by KiranBaliga**
closes #108 

This is a small contribution towards adding an automated greetings bot. Thank you. Please share the feedback.

### CODE REVIEW

**Comment by 07sumit1002** [comment]
Before submitting the request, could you please share a screen-recorded video demonstrating how it is working?

**Comment by KiranBaliga** [comment]
@07sumit1002 I have used a secondary testing account to test the forked repo. Link : https://github.com/KiranBaliga/CabRental/pull/1

The bot has passed the check and displays the message for a new PR or issue. Please review.

**Comment by KiranBaliga** [comment]
@07sumit1002 Please review the link above for the bot message displayed using forked repo & a testing account. Thank you! Please add level1 and WOB24 labels.

**Comment by MastanSayyad** [comment]
@KiranBaliga given

**Pull request merged**
