### PR TITLE
Added the holiday packages

### PR DESCRIPTION
**Pull request by chmp0940**
I had  a additional section of holiday packages which takes all info and also added some trending holidays and the other holidays

# 🚀 Pull Request

## Description

Please include a summary of the changes and the related issue. Provide relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue) #197 

## Added Holiday packages

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation Update

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

## Screenshot of final output/video
Screenshot 2024-10-07 004833

### CODE REVIEW

**Comment by chmp0940** [comment]
I am not able to solve conflicts ,it may be due to light and dark mode issues

**Comment by 07sumit1002** [comment]
Pull the latest code and then work on it
This is having some conflicts, resolve and then recreate the PR

**Comment by chmp0940** [comment]
can you pls tell why this conflict is happening

**Comment by chmp0940** [comment]
why this is giving me this conflict 
image

**Comment by chmp0940** [comment]
still not getting about conflicts pls help if possible 1

**Pull request closed without merging**
