### PR TITLE
Revamp the About Us Page for Better User Engagement

### PR DESCRIPTION
**Pull request by snehhhcodes**
# 🚀 Pull Request

## Description

Hello Sumit !!

First of all Thank you once for assigning me this task!
I’m excited to share that I have completed the work I was assigned with.

~~ What does this PR do?
This PR enhances the "About Us" page by integrating its content directly on the homepage. It replaces the static, text-heavy design with a more engaging and visually appealing format, including the addition of a video for better user interaction with a clear understanding of the website's objectives.

~~ Why is this PR needed?
The current "About Us" page feels disconnected and overwhelming due to the excessive amount of text and large, unengaging images. This leads to user disengagement, as most visitors are likely to skip reading the entire page. By integrating the content on the homepage, we can capture users' attention more effectively and ensure they understand the website’s purpose quickly.

~~ How does this PR address the issue?
The PR makes the content more concise by reducing the text and presenting it in a more visually appealing way, with the addition of a video. This creates a seamless user experience where visitors can grasp the website’s objectives without needing to navigate to a separate page. The result is a more dynamic, integrated homepage that better retains user interest.
Fixes # (issue)

## Type of Change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

## Screenshot of final output/video
[373542794-545909e1-be22-421b-b63d-bbaa6fdde8c8.webm](https://github.com/user-attachments/assets/bd810279-8298-4c31-82ee-addc1bb54504)

### CODE REVIEW

**Comment by snehhhcodes** [comment]
@07sumit1002 Hey I resolved the merge conflict please review it once again.
Thankyou for your understanding

**Comment by snehhhcodes** [comment]
@07sumit1002 would be great if you add label and level for gssoc and hacktoberfest

**Comment by 07sumit1002** [comment]
{C9171EE3-AF78-46AB-9160-463542FB7A5D}
Please try to check the UI on your own before creating the PR

**Comment by snehhhcodes** [comment]
> What will happen to about us page?

As i have already mentioned in the issue the previous"About Us" page feels disconnected, it includes more information than necessary, the large images make it appear boring, leading to disengagement. 
Users find it boring and often do not read through the extensive text.

Instead of having a separate "About Us" page, we integrate this content directly on the homepage. Added a video which can enhance engagement while reducing the amount of text to make it more digestible. This approach will provide users with a quick and engaging overview of the website's purpose.

**Comment by snehhhcodes** [comment]
@07sumit1002 bro labels are not updates yet??

**Comment by 07sumit1002** [comment]
@snehhhcodes Is it fine now

**Comment by snehhhcodes** [comment]
> @snehhhcodes Is it fine now

label is not fine sumit it should be like level2 without any space

**Comment by snehhhcodes** [comment]
oke lol tho now gssoc-ext label is incorrect it should be small not in caps like (gssoc-ext)

**Comment by snehhhcodes** [comment]
> @07sumit1002  oke lol tho now gssoc-ext label is incorrect it should be small not in caps like (gssoc-ext)

**Comment by snehhhcodes** [comment]
@07sumit1002 please correct the gssoc ext label it should be in small letter (gssoc-ext) not like GSSOC-EXT

it is not counting in leaderboard

**Comment by 07sumit1002** [comment]
@snehhhcodes can you check if now the labels are fine?

**Pull request merged**
