### PR TITLE
Change Twitter Symbol to X in footer section #143

### PR DESCRIPTION
**Pull request by rakeshkushwaha332**
initial

I have replaced the twitter logo with X logo
final

### CODE REVIEW

**Comment by rakeshkushwaha332** [comment]
@07sumit1002 , could you please add the `gssoc-extd` label to this issue?

**Comment by Manishkumarsingh41** [comment]
before

I have replaced the twitter logo with X logo and also instagram logo and 
car rental logo of website
after

**Comment by Manishkumarsingh41** [comment]
@07sumit1002 ,Could you please add the gssoc-extd label to this issue?

**Comment by Manishkumarsingh41** [comment]
@07sumit1002 , could you please add the gssoc-extd label to this issue?

**Pull request merged**
