### PR TITLE
headername added

### PR DESCRIPTION
**Pull request by Krishnamverma951**
Hello PA 
I have added the headername with the logo properly

image

### CODE REVIEW

**Comment by 07sumit1002** [comment]
@Krishnamverma951 This is having some conflicts resolve and then recreate the PR

**Comment by Krishnamverma951** [comment]
hi sir 
please assign me label

**Comment by Krishnamverma951** [comment]
@MastanSayyad @sumit Kumar
Cab rental of my first pull request  which was created in2 or 3weeks ago 
But my pr not reflect on leader board please help me

**Comment by MastanSayyad** [comment]
@Krishnamverma951 to reflect the PR and the score on the leaderboard your PR must have the labels on it, such as `gssoc-ext` `level1` `level2` `level3`

**Pull request merged**
