### PR TITLE
Issue 112 - Complicated file structure (solved)

### PR DESCRIPTION
**Pull request by DarshanKrishna-DK**
# Issue 112 - Complicated file structure (solved)

## Description

This pull request addresses the issue of a complex file structure in the project. By reorganizing the files into more logical categories (HTML, CSS, JavaScript, and PHP files), I have improved code readability and maintainability.

## Type of Change

- File Structure Simplification: Categorized similar files into their respective folders, enhancing project organization.
- Updated File Paths: Adjusted image and file paths within the code to reflect the new file structure, ensuring accurate references.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings or errors

(Request you to consider this pull request and add hacktoberfest & gssoc lables. Thank you!)

### CODE REVIEW

**Comment by 07sumit1002** [comment]
{8F1E7459-4EC8-4167-AB8E-D1DA4B01CC42}
This is having some conflicts, resolve and then recreate the PR
Pull the latest code and then work on it

**Comment by DarshanKrishna-DK** [comment]
Hey @07sumit1002. The merge conflicts will keep on arising because i have changed the file structure and hence the file & image paths are also modified. 

So do not accept any pull request until today EOD. I will solve the merge conflicts and create a new pull request. Do make sure that you check my mofified pull request before any other, if not the merge conflicts will again rise.

**Comment by 07sumit1002** [comment]
@DarshanKrishna-DK Ok From this point on i am not merging any PRs for the next 24 hrs.

**Comment by DarshanKrishna-DK** [comment]
> @DarshanKrishna-DK Ok From this point on i am not merging any PRs for the next 24 hrs.

Ok thank you! 
Will create a new pull request by tomorrow 7AM.

**Pull request closed without merging**
