### PR TITLE
Enhanced the about page

### PR DESCRIPTION
**Pull request by jyothimanoj12**
**   fixed issue #208  **

updated the about.html

1. Enhanced Navigation Bar
Black Underline Hover Effect: I added a subtle yet effective black underline when users hover over the menu items in the navbar. This creates a clear visual cue, making the navigation more interactive and user-friendly.
Added an Image to the Navbar: Including a logo or image in the navbar helps reinforce brand identity and makes the header more visually engaging. The image is positioned next to the company logo, ensuring it's visible without overwhelming the other elements.

2. Image Customization
Updated Images: The images in the "About Us" section were swapped for higher-quality, more relevant visuals

Screenshot 2024-10-06 150247

3. Text and Content Improvement
Clearer Sections: I reorganized the content into clearly defined sections (Company Overview, Mission & Vision, and Values & Principles) to make the page easy to scan.
Better Typography: Adjusted font sizes, colors, and added bold sections to highlight key information, making the content more readable and visually appealing.

Screenshot 2024-10-06 150315

Screenshot 2024-10-06 150333

4. Added a footer section

Screenshot 2024-10-06 150344

### CODE REVIEW

**Comment by jyothimanoj12** [comment]
can you add gsoc extended , hacktober accepted and level 2 tag

**Comment by jyothimanoj12** [comment]
#208

**Comment by jyothimanoj12** [comment]
also can you see whether you have used the correct hacktober-accepted tag , since  its showing like this on my website
Screenshot 2024-10-06 212550

**Comment by 07sumit1002** [comment]
@jyothimanoj12 Can you recheck now and confirm wether it is still showing this or not?

**Comment by jyothimanoj12** [comment]
> @jyothimanoj12 Can you recheck now and confirm wether it is still showing this or not?

Yes its showing now , thank you

**Pull request merged**
