### PR TITLE
Issue 112 - Complicated file structure (solved)

### PR DESCRIPTION
**Pull request by DarshanKrishna-DK**
# Issue 112 - Complicated file structure (solved)

## Description

This pull request addresses the issue of a complex file structure in the project. By reorganizing the files into more logical categories (HTML, CSS, JavaScript, and PHP files), I have improved code readability and maintainability.

## Type of Change

- File Structure Simplification: Categorized similar files into their respective folders, enhancing project organization.
- Updated File Paths: Adjusted image and file paths within the code to reflect the new file structure, ensuring accurate references.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings or errors

`(Request you to consider this pull request and add hacktoberfest & gssoc lables. Thank you!)`

### CODE REVIEW

**Comment by DarshanKrishna-DK** [comment]
Hey @07sumit1002! 
I have closed the previous pull request and created this new pull request after modifying all the merge conflicts. 

Do add the hacktoberfest and gssoc-extd labels for my issue #112 
Consider updating the issue from level 1.

Thank you!

**Comment by DarshanKrishna-DK** [comment]
Hey @07sumit1002. Isn't this repo a part of hacktoberfest?

**Comment by DarshanKrishna-DK** [comment]
@akbatra567 Can you let me know what was the issue with my pull request and why was it reverted?

**Comment by akbatra567** [comment]
> @akbatra567 Can you let me know what was the issue with my pull request and why was it reverted?

Hey @DarshanKrishna-DK, I am not the right person for this query. 

@07sumit1002, has reverted the PR, I'm not aware of the specific reason myself.

**Pull request merged**
