### PR TITLE
Update issue templates #122

### PR DESCRIPTION
**Pull request by nagajaideep**
THIS PULL REQUEST MAKES THE FOLLOWING CHANGES
-Fixes issue #122 : added the 3 templates of bug,feature and pull request templates

### CODE REVIEW

**Comment by 07sumit1002** [comment]
@nagajaideep This is having some conflicts resolve and then recreate the PR

**Comment by nagajaideep** [comment]
yeah sure ill i will review it once @07sumit1002

**Comment by nagajaideep** [comment]
hey the confilict is resolved can you review it once and approve the Pull Req @07sumit1002

**Comment by nagajaideep** [comment]
i was checking the features @07sumit1002 close this issue after reviewing it

**Pull request merged**
