### PR TITLE
Update Navs

### LINKED ISSUE #236: [Improving home page styling]
Hey I believe that you website could do better with some styling improvements.
Such as,
Screenshot 2024-10-06 at 1 51 07 PM
The red outline around the details to be filled is not looking good so I could find a better way to do it better.
Also the boxes have strict corners which would look better with some round corners.
And the when we hover over the book now button, the whole button comes up but what I think would be better is if we hover over the button, the book now text gets bigger not the whole button maintaining the aesthetics of the website.

@07sumit1002 Please assign me this issue so that I could make it better.

### PR DESCRIPTION
**Pull request by pranusri1903**
# 🚀 Pull Request 
Issue : [Improving home page styling]  closes #236

**Making Nav Bar consistent across pages**

This PR standardizes the navigation bar across all pages of the website. The previous navbar design was inconsistent, with different styling and font choices on various pages, which made the user experience messy and disjointed. This update ensures a clean, uniform look and feel for the navbar, enhancing usability and visual coherence throughout the site.

Key Changes:

Applied consistent styling (font, size, spacing) to the navbar across all pages.
Standardized the following links in the navbar: Home, Ride Services, and other relevant pages.
Cleaned up unused or conflicting CSS related to the navbar on individual pages.
Why this is important: This change improves the overall user experience by providing a seamless navigation experience, making the site look more professional and easier to use.

### CODE REVIEW

**Comment by pranusri1903** [comment]
@07sumit1002 please check the pull request as the code in your repo has a lot of missing files and i have to start working on another issue on the same project and i need to to fork the latest project for that. The current repo has many files missing hence it would be hard to work on it.

**Review by pranusri1903 — COMMENTED** [review]
@07sumit1002 Please Review the pull request and merge asap.

**Comment by pranusri1903** [comment]
I have made all the necessary changes in the files.
Please review it!
@07sumit1002

**Comment by pranusri1903** [comment]
@akbatra567  Sumit has asked me to ask you to review it as he is unavailable right now.

**Comment by akbatra567** [comment]
Hey @subin-shk, 
You might see some merge conflicts after this PR merges and you would see some overlap. 
Please do have a look. https://github.com/07sumit1002/CabRental/issues/247

**Comment by subin-shk** [comment]
@akbatra567 just close it then. next time tell people of the issue had already been assigned as i see that the task for making consistent navbar had already been assigned to someone lese.

**Comment by akbatra567** [comment]
> @akbatra567 just close it then. next time tell people of the issue had already been assigned as i see that the task for making consistent navbar had already been assigned to someone lese.

@subin-shk, It seems similar but it is not. Even if this PR is merged there are a lot of inconsistencies around the navbar across all pages so your issue is still valid. I tagged you just in case it would give a merge conflict issue.

**Pull request merged**
