### PR TITLE
Done Changes with responsiveness

### LINKED ISSUE #132: Responsiveness of Website
This project is not responsive not evn compatible for mobile phones . I can make this project responsive and user friendly . Please assign this project to me. also add hacktoberfest and gssoc labels.

### PR DESCRIPTION
**Pull request by Khushi-Nigam**
# 🚀 Pull Request

Fixes #132 
Fixed navbar, contactus and customer reviews section

Screenshot 2024-10-05 135149
image

### CODE REVIEW

**Comment by 07sumit1002** [comment]
@Khushi-Nigam This is having some conflicts, resolve and then recreate the PR

**Comment by Khushi-Nigam** [comment]
@07sumit1002  Can you Please add hacktoberfest  gssocextd and level label

**Comment by 07sumit1002** [comment]
@Khushi-Nigam Sorry but this is not level 3 you removed the comment closing tag (-->) from index.html which led to damage of the whole page. So I can only assign it level 1.

**Comment by Khushi-Nigam** [comment]
@07sumit1002 Please add labels properly write everything , I have asked Program manager also  
image
Please write in small letters as points are not counted in leaderboard due to this

**Pull request merged**
